#!/usr/bin/env bash
# Collects the licences of everything that ships inside the binary.
#
# The frontend is compiled into `seid`, so a release is not just this
# project's code: it carries Angular, uPlot, the IBM Plex fonts, the
# MySQL driver and half a dozen others. MIT, BSD and the Open Font
# Licence all say the same thing about that - pass the notice on with
# the copy - and none of them care that the copy happens to be one
# static file.
#
#   tools/licenses/collect.sh          write THIRD-PARTY-NOTICES.md
#   tools/licenses/collect.sh --check  fail if it is out of date
#
# Go modules come from `go list -deps`, which is what actually links,
# rather than `go mod` which also lists test-only dependencies. The
# frontend list is the runtime dependencies from package.json; the build
# tooling around them does not ship.
set -euo pipefail

cd "$(dirname "$0")/../.."
out="THIRD-PARTY-NOTICES.md"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

license_file() {
  ls "$1" 2>/dev/null | grep -iE '^(license|licence|copying)(\.(txt|md))?$' | head -1
}

# Not every licence file ends in a newline - tslib's does not - and a
# closing fence appended to the last line of one is a fence that does
# not close. awk adds the missing newline; tr drops the CRLFs some of
# them carry.
emit_licence() {
  tr -d '\r' < "$1" | awk 1
}

{
  cat <<'HEADER'
# Third-party notices

The Statusengine Web Interface ships as a single binary with the
frontend compiled into it, so a release carries the software below as
well as its own. Their licences are reproduced in full, which is what
those licences ask for.

This file is generated by `tools/licenses/collect.sh`. Do not edit it by
hand; run the script.

HEADER

  echo "## Go"
  echo
  go list -deps -f '{{if .Module}}{{.Module.Path}}|{{.Module.Version}}|{{.Module.Dir}}{{end}}' ./... \
    | sort -u | grep -v '^$' | grep -v '^github.com/statusengine/interface' \
    | while IFS='|' read -r path version dir; do
        file="$(license_file "$dir")"
        echo "### $path $version"
        echo
        if [ -n "$file" ]; then
          echo '```text'
          emit_licence "$dir/$file"
          echo '```'
        else
          echo "No licence file in the module. See <https://$path>."
        fi
        echo
      done

  echo "## Frontend"
  echo
  node -e '
    const pkg = require("./frontend/package.json");
    process.stdout.write(Object.keys(pkg.dependencies).join("\n"));
  ' | while read -r name; do
        dir="frontend/node_modules/$name"
        version="$(node -e "process.stdout.write(require('./$dir/package.json').version)" 2>/dev/null || echo "")"
        file="$(license_file "$dir")"
        echo "### $name $version"
        echo
        if [ -n "$file" ]; then
          echo '```text'
          emit_licence "$dir/$file"
          echo '```'
        else
          echo "No licence file in the package. See <https://www.npmjs.com/package/$name>."
        fi
        echo
      done
} > "$tmp"

if [ "${1:-}" = "--check" ]; then
  if ! diff -q "$tmp" "$out" > /dev/null 2>&1; then
    echo "$out is out of date. Run tools/licenses/collect.sh." >&2
    diff -u "$out" "$tmp" | head -40 >&2 || true
    exit 1
  fi
  echo "$out is current"
  exit 0
fi

mv "$tmp" "$out"
trap - EXIT

# Counted from the lists rather than from the headings in the file: a
# licence text of its own can contain a line that looks like a heading,
# and yaml.v3's does.
go_count="$(go list -deps -f '{{if .Module}}{{.Module.Path}}{{end}}' ./... \
  | sort -u | grep -v '^$' | grep -cv '^github.com/statusengine/interface')"
js_count="$(node -e 'process.stdout.write(String(Object.keys(require("./frontend/package.json").dependencies).length))')"
echo "wrote $out: $go_count Go modules, $js_count frontend packages, $(wc -l < "$out") lines"
